In [1]:
import pandas as pd
import numpy as np

In [2]:
WineData = pd.read_csv("red-wine-quality.csv")

In [3]:
WineData.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
x = WineData.iloc[:,0:12]
y = WineData["quality"]

In [5]:
WineData.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [6]:
x = pd.DataFrame(x)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=18)

In [9]:
model1 = RandomForestClassifier()

In [10]:
model1.fit(X_train,y_train)

RandomForestClassifier()

In [11]:
model1.score(X_test,y_test)

0.98125

In [12]:
model1.predict(X_test)

array([4, 5, 5, 5, 7, 6, 5, 5, 5, 7, 5, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 7, 5, 7, 5, 6, 5, 6, 5, 5, 5, 7, 6, 6, 5, 7, 6, 6, 5, 5, 6,
       5, 5, 7, 6, 5, 6, 5, 5, 6, 5, 5, 7, 5, 5, 7, 7, 5, 5, 7, 6, 6, 5,
       7, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 7, 5, 7, 5, 6, 5, 5, 5, 5, 6,
       7, 6, 5, 6, 5, 6, 6, 6, 7, 7, 6, 6, 5, 6, 5, 7, 5, 6, 5, 6, 5, 5,
       6, 6, 6, 6, 7, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 7, 6, 6, 7, 5, 5, 5,
       6, 5, 5, 5, 7, 6, 6, 6, 6, 6, 7, 5, 6, 5, 5, 4, 6, 6, 5, 5, 5, 5,
       4, 6, 7, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 7, 6, 5, 5, 5, 5,
       6, 5, 7, 5, 6, 5, 6, 6, 7, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6,
       5, 5, 7, 5, 4, 6, 6, 6, 5, 5, 6, 4, 6, 4, 5, 5, 6, 6, 5, 6, 6, 7,
       6, 5, 6, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 6, 5, 7, 5, 6, 5, 4, 5, 4,
       7, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 4,
       5, 7, 6, 6, 5, 5, 5, 6, 4, 6, 7, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 7, 5, 6, 6, 6, 6, 6, 6, 5, 5, 4, 5, 5, 6,

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
model2 =  DecisionTreeClassifier()

In [15]:
model2.fit(X_train,y_train)

DecisionTreeClassifier()

In [16]:
model2.score(X_test,y_test)

1.0

In [17]:
model2.predict(X_test)

array([4, 5, 5, 5, 7, 6, 5, 5, 5, 7, 5, 5, 6, 5, 6, 5, 6, 6, 4, 6, 6, 5,
       5, 6, 8, 5, 7, 5, 6, 5, 6, 5, 5, 5, 7, 6, 6, 5, 7, 6, 6, 5, 5, 6,
       5, 5, 7, 6, 5, 6, 5, 5, 6, 5, 5, 7, 5, 5, 7, 7, 5, 5, 7, 6, 6, 5,
       7, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 7, 5, 7, 5, 6, 5, 5, 5, 5, 6,
       7, 6, 5, 6, 5, 6, 6, 6, 7, 7, 6, 6, 5, 6, 5, 7, 5, 6, 5, 6, 5, 5,
       6, 6, 6, 6, 7, 5, 6, 6, 6, 6, 5, 5, 6, 6, 5, 7, 6, 6, 7, 5, 5, 5,
       6, 5, 5, 5, 7, 6, 6, 6, 6, 6, 7, 5, 6, 5, 5, 4, 6, 6, 5, 5, 5, 5,
       3, 6, 7, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 7, 6, 5, 5, 5, 5,
       6, 5, 7, 5, 6, 5, 6, 6, 7, 6, 5, 7, 6, 6, 5, 6, 6, 6, 6, 5, 6, 6,
       5, 5, 7, 5, 4, 6, 6, 6, 5, 5, 6, 4, 6, 4, 5, 5, 6, 6, 5, 6, 6, 7,
       6, 5, 6, 5, 6, 6, 6, 6, 7, 5, 6, 5, 6, 6, 5, 7, 5, 6, 5, 4, 5, 4,
       7, 5, 5, 6, 6, 4, 6, 5, 6, 6, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 4,
       5, 7, 6, 6, 5, 5, 5, 6, 3, 6, 7, 5, 5, 5, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 7, 5, 6, 6, 6, 6, 6, 6, 5, 5, 4, 5, 5, 6,

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
model3 = KNeighborsClassifier()

In [20]:
model3.fit(X_train,y_train)

KNeighborsClassifier()

In [21]:
model3.score(X_test,y_test)

0.6041666666666666

In [22]:
model3.predict(X_test)

array([5, 5, 6, 6, 6, 5, 5, 5, 5, 7, 5, 5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 7, 5, 7, 6, 5, 6, 6, 5, 6, 5, 7, 6, 5, 5, 5, 5, 6, 5, 5, 5,
       5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 7, 5, 6, 6, 5, 5, 5, 6, 6, 6, 6,
       5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 5, 5, 6, 6, 6, 5, 6, 7, 7, 6, 6, 6, 5, 5, 6, 5, 5, 5, 5, 6, 5,
       5, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 5, 6, 6, 6, 5,
       6, 5, 5, 4, 6, 6, 6, 6, 6, 6, 6, 5, 7, 6, 5, 4, 5, 5, 5, 5, 6, 5,
       5, 5, 7, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 7, 6, 5, 5, 5, 5,
       5, 6, 7, 5, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 5, 5, 6, 5, 7, 5, 5, 5, 6, 5, 6, 6, 6, 7,
       6, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 7, 6, 6, 6, 5, 6, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 5, 6, 6, 5, 6, 6, 6, 6, 7, 5, 5,
       5, 6, 5, 6, 5, 5, 5, 6, 4, 6, 7, 5, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5,
       6, 7, 5, 5, 5, 6, 7, 6, 5, 5, 5, 5, 5, 5, 6,